apiVersion: v1
kind: Service
metadata:
  name: ecommerce-app-service
spec:
  selector:
    app: ecommerce-app     # must match Deployment's Pod labels
  ports:
    - port: 5200
      targetPort: 5200
  type: LoadBalancer           # or NodePort / LoadBalancer to reach it externally